import React, {useEffect, useMemo, useState} from "react";
import {ArrowRight, Bot, CalendarDays, Check, ChevronRight, CircleDollarSign, Compass, Download, Home, Map, Mic, Mountain, Navigation, Plus, RefreshCw, Sparkles, Split, Users, Wallet, Zap, CloudRain, Hotel, Plane, Utensils, ShieldCheck, Play, UserRound, Link2, Menu, X} from "lucide-react";

const API=import.meta.env.VITE_API_URL||"http://localhost:5050/api";
const A = `${import.meta.env.BASE_URL}assets/`;
const defaultTrip={destination:"Andhra Pradesh",days:4,budget:18000,pace:"Relaxed",interests:["Heritage","Food","Nature"]};
const nav=[
 ["dashboard","Command Center",Home],["create","Create Trip",Sparkles],["itinerary","Itinerary",CalendarDays],
 ["map","Smart Route",Map],["group","Group Hub",Users],["bookings","Execution Hub",Plane],["budget","Budget & Split",Wallet],["dna","Travel DNA",UserRound]
];
function money(n){return `₹${Number(n||0).toLocaleString("en-IN")}`}

export default function App(){
 const [page,setPage]=useState("dashboard"),[trip,setTrip]=useState(defaultTrip),[plan,setPlan]=useState(()=>JSON.parse(localStorage.getItem("tripbuddy-plan")||"null"));
 const [members,setMembers]=useState([{name:"You",preferences:["Heritage","Food","Nature"]},{name:"Aarav",preferences:["Nature","Food"]},{name:"Meera",preferences:["Heritage","Culture"]}]);
 const [toast,setToast]=useState(""); const [loading,setLoading]=useState(false); const [health,setHealth]=useState(false); const [mobile,setMobile]=useState(false);
 useEffect(()=>{fetch(`${API}/health`).then(r=>r.ok&&setHealth(true)).catch(()=>setHealth(false))},[]);
 useEffect(()=>{if(plan)localStorage.setItem("tripbuddy-plan",JSON.stringify(plan))},[plan]);
 useEffect(()=>{if(toast){let t=setTimeout(()=>setToast(""),3000);return()=>clearTimeout(t)}},[toast]);
 async function generate(){setLoading(true);setPage("agent");try{let r=await fetch(`${API}/trips/plan`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(trip)});let d=await r.json();setPlan(d.plan);setPage("itinerary");setToast("AI copilot finished your first-pass plan.")}catch{setToast("Backend unavailable — start the API on port 5050.");setPage("create")}finally{setLoading(false)}}
 const goto=x=>{setPage(x);setMobile(false)};
 return <div className="app">
  <aside className={`sidebar ${mobile?"show":""}`}>
   <div className="brand"><div className="brandmark"><Compass size={20}/></div><div><b>tripbuddy</b><span>agentic travel copilot</span></div><button className="close-mobile" onClick={()=>setMobile(false)}><X size={17}/></button></div>
   <div className="side-label">WORKSPACE</div>{nav.map(([id,label,Icon])=><button key={id} className={`nav ${page===id?"active":""}`} onClick={()=>goto(id)}><Icon size={17}/>{label}</button>)}
   <div className="side-bottom"><div className="mini-card"><div className="mini-icon"><Zap size={15}/></div><div><b>{health?"AI engine ready":"API offline"}</b><span>{health?"5 agents online":"Start backend"}</span></div></div><div className="team"><img src={A+"kaizenx.png"}/><div><b>KaizenX</b><span>SIH 2026 · TRV22</span></div></div></div>
  </aside>
  {mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>} 
  <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu size={18}/></button><div className="crumb"><span>TripBuddy</span><ChevronRight size={14}/><b>{nav.find(n=>n[0]===page)?.[1]||"Agent Run"}</b></div><div className="top-actions"><span className="live"><i/> {health?"Live API":"Demo mode"}</span><button className="avatar">HK</button></div></header>
  <div className="content">
   {page==="dashboard"&&<Dashboard goto={goto} plan={plan} health={health}/>} 
   {page==="create"&&<CreateTrip trip={trip} setTrip={setTrip} onGenerate={generate}/>} 
   {page==="agent"&&<AgentRun trip={trip} loading={loading}/>} 
   {page==="itinerary"&&<Itinerary plan={plan} setPlan={setPlan} goto={goto} toast={setToast}/>} 
   {page==="map"&&<SmartRoute plan={plan} goto={goto}/>} 
   {page==="group"&&<GroupHub members={members} setMembers={setMembers} toast={setToast}/>} 
   {page==="bookings"&&<ExecutionHub plan={plan} toast={setToast}/>} 
   {page==="budget"&&<Budget plan={plan} members={members} toast={setToast}/>} 
   {page==="dna"&&<TravelDNA trip={trip} setTrip={setTrip}/>} 
  </div></main>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}

function Dashboard({goto,plan,health}){return <section>
 <div className="hero"><div className="hero-copy"><span className="pill bright">SIH 2026 · SIH26207 · TOURISM</span><h1>Travel planning,<br/><em>finally intelligent.</em></h1><p>TripBuddy is an agentic AI copilot that <b>plans, optimises, executes and adapts</b> your journey around your preferences, budget and group.</p><div className="hero-actions"><button className="primary big" onClick={()=>goto("create")}>Create my trip <ArrowRight size={17}/></button><span className="trust"><Check size={14}/> {health?"Backend connected":"Demo-safe mode"}</span></div></div><div className="hero-art"><img src={A+"tripbuddy-concept.png"}/><div className="agent-badge"><span className="pulse"/><div><b>5 agents</b><small>Travel DNA · Route · Group · Budget · Itinerary</small></div></div></div></div>
 <div className="section-head"><div><div className="eyebrow">THE DIFFERENTIATOR</div><h2>One copilot. The whole journey.</h2></div><button className="ghost" onClick={()=>goto("create")}>Start planning <ArrowRight size={15}/></button></div>
 <div className="feature-grid"><Feature icon={UserRound} title="Travel DNA" text="Builds a deep profile from pace, tastes, budget and priorities."/><Feature icon={Navigation} title="Smart Route" text="Clusters activities geographically to reduce transit friction."/><Feature icon={Users} title="Group Consensus" text="Mediates conflicting preferences instead of forcing one plan."/><Feature icon={RefreshCw} title="Self-Healing" text="Repairs plans when delays, weather or disruptions hit."/></div>
 <div className="showcase"><div className="showcase-copy"><span className="pill">AGENTIC LOOP</span><h3>From “Top 10” lists to a living travel plan.</h3><p>The product converts messy inputs into structured constraints, reasons across them, then keeps the plan adaptable.</p><div className="metrics"><Metric n="01" t="Understand" d="Text · voice · link"/><Metric n="02" t="Reason" d="DNA · route · group"/><Metric n="03" t="Act" d="Plan · adapt · split"/></div></div><div className="visual"><img src={A+"travel-dna.png"}/><div className="floating"><Bot size={15}/><span>Agent status</span><b>Personalisation active</b></div></div></div>
 {plan&&<div className="last-plan"><div><span className="pill">LATEST PLAN</span><h3>{plan.destination} · {plan.days} days</h3><p>{plan.itinerary.length} experiences · {money(plan.estimated)} estimated · {plan.savings?money(plan.savings)+" buffer":"budget optimised"}</p></div><button className="primary" onClick={()=>goto("itinerary")}>Open itinerary <ArrowRight size={15}/></button></div>}
 <div className="judge-strip"><div><ShieldCheck size={19}/><b>Built for a live SIH demo</b><span>Every major capability has an interactive path.</span></div><div><Sparkles size={19}/><b>No paid API required</b><span>Demo-safe intelligence keeps the pitch reliable.</span></div><div><Zap size={19}/><b>Production-ready seams</b><span>Provider adapters can replace demo services later.</span></div></div>
 </section>}
function Feature({icon:Icon,title,text}){return <div className="feature card"><div className="feature-icon"><Icon size={18}/></div><h3>{title}</h3><p>{text}</p><span className="linkish">AI capability <ArrowRight size={13}/></span></div>}
function Metric({n,t,d}){return <div><b>{n}</b><strong>{t}</strong><span>{d}</span></div>}
function PageTitle({eyebrow,title,sub}){return <div className="page-title"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>}

function CreateTrip({trip,setTrip,onGenerate}){
 const [input,setInput]=useState("");const [recording,setRecording]=useState(false);const toggle=x=>setTrip({...trip,interests:trip.interests.includes(x)?trip.interests.filter(i=>i!==x):[...trip.interests,x]});
 async function parse(){if(!input)return;try{let r=await fetch(`${API}/input/parse`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:input})});let d=await r.json();setTrip({...trip,...d.parsed});}catch{}}
 function voice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setRecording(true);setTimeout(()=>setRecording(false),1800);return}const s=new SR();s.lang="en-IN";s.onstart=()=>setRecording(true);s.onend=()=>setRecording(false);s.onresult=e=>setInput(e.results[0][0].transcript);s.start()}
 return <section><PageTitle eyebrow="MULTI-MODAL INPUT" title="Tell TripBuddy what you want." sub="Start with constraints. The copilot turns them into an executable trip brief."/>
 <div className="input-banner card"><div className="input-banner-icon"><Sparkles size={19}/></div><div><b>Fast brief mode</b><p>Try: “4 days in Goa, ₹20,000, relaxed, food + beaches + heritage.”</p></div><button className="secondary" onClick={parse}><Bot size={15}/> Parse brief</button></div>
 <div className="create-grid"><div className="card form-card"><label>Natural-language brief</label><div className="brief-input"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Describe the trip in your own words…"/><button className={recording?"recording mic-btn":"mic-btn"} onClick={voice}><Mic size={17}/></button></div><div className="form-divider">or configure directly</div>
 <label>Destination</label><div className="input-wrap"><Map size={16}/><input value={trip.destination} onChange={e=>setTrip({...trip,destination:e.target.value})}/></div><div className="two"><div><label>Days</label><input type="number" min="2" max="7" value={trip.days} onChange={e=>setTrip({...trip,days:e.target.value})}/></div><div><label>Budget</label><div className="input-wrap"><span>₹</span><input type="number" value={trip.budget} onChange={e=>setTrip({...trip,budget:e.target.value})}/></div></div></div>
 <label>Travel pace</label><div className="seg">{["Relaxed","Balanced","Fast"].map(x=><button key={x} className={trip.pace===x?"sel":""} onClick={()=>setTrip({...trip,pace:x})}>{x}</button>)}</div><label>Interests</label><div className="chips">{["Heritage","Food","Nature","Culture","Adventure","Shopping"].map(x=><button key={x} className={trip.interests.includes(x)?"chip on":"chip"} onClick={()=>toggle(x)}>{trip.interests.includes(x)&&<Check size={12}/>} {x}</button>)}</div><div className="input-wrap link-input"><Link2 size={16}/><input placeholder="Paste a Reels / inspiration link (demo parser)"/></div><button className="primary full" onClick={onGenerate}><Sparkles size={16}/> Build my trip</button></div>
 <div className="side-preview"><div className="preview-card"><div className="preview-top"><span className="pill">AI BRIEF</span><Bot size={18}/></div><h3>{trip.destination}</h3><p>{trip.days} days · {trip.pace} · {trip.interests.join(" · ")}</p><div className="brief-row"><span>Budget guard</span><b>{money(trip.budget)}</b></div><div className="brief-row"><span>Planning agents</span><b>5 online</b></div><div className="brief-row"><span>Input modes</span><b>Text · Voice · Link</b></div><div className="brief-row"><span>Output</span><b>Adaptive itinerary</b></div></div><img className="side-image" src={A+"agent-flow.jpg"}/><div className="privacy card"><ShieldCheck size={16}/><div><b>Judge-friendly demo</b><p>No login or payment credentials needed to explore the core flow.</p></div></div></div></div></section>}

function AgentRun({trip}){const steps=["Reading your travel brief","Building Travel DNA","Optimising route clusters","Checking budget constraints","Mediating group preferences","Generating adaptive itinerary"];return <section className="agent-page"><div className="agent-center"><div className="orb"><Bot size={40}/></div><span className="pill bright">AGENTIC RUN</span><h1>TripBuddy is thinking.</h1><p>Turning your brief into an executable travel plan for <b>{trip.destination}</b>.</p><div className="agent-steps">{steps.map((x,i)=><div key={x} className="agent-step"><span className="check-dot">{i<4?<Check size={12}/>:<span className="spin"/>}</span><span>{x}</span><small>{i<4?"DONE":"RUNNING"}</small></div>)}</div></div></section>}

function Itinerary({plan,setPlan,goto,toast}){if(!plan)return <Empty goto={goto}/>;async function heal(){let r=await fetch(`${API}/trips/self-heal`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itinerary:plan.itinerary,disruption:"Heavy rain + 70 min delay"})});let d=await r.json();setPlan({...plan,itinerary:d.itinerary});toast("Self-healing complete — disrupted slot repaired.")};function exportPlan(){let txt=`TripBuddy — ${plan.destination}\n${plan.days} days · ${plan.pace}\nEstimated: ${money(plan.estimated)}\n\n`+plan.itinerary.map(x=>`${x.day} | ${x.city} | ${x.title} | ${x.tag} | ${money(x.cost)}`).join("\n");let blob=new Blob([txt],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="tripbuddy-itinerary.txt";a.click();URL.revokeObjectURL(a.href)}return <section><PageTitle eyebrow="ADAPTIVE ITINERARY" title={`${plan.destination}, designed around you.`} sub={`${plan.days} days · ${plan.pace} pace · ${plan.itinerary.length} curated experiences`}/><div className="itinerary-head"><div className="route"><Navigation size={16}/>{plan.route.join(" → ")}</div><div><button className="secondary" onClick={heal}><CloudRain size={15}/> Simulate disruption</button><button className="ghost" onClick={exportPlan}><Download size={15}/> Export</button><button className="primary" onClick={()=>goto("bookings")}><Plane size={15}/> Execute trip</button></div></div><div className="itinerary-layout"><div className="timeline">{plan.itinerary.map((x,i)=><div className={`timeline-item ${x.status==="rescheduled"?"repaired":""}`} key={x.id}><div className="time-dot">{i+1}</div><div className="item-card"><div className="item-meta"><span>{x.day}</span><span>{x.city}</span><span className="tag">{x.tag}</span><span>{x.time}</span></div><h3>{x.title}</h3><p>{x.duration} · {x.cost?money(x.cost):"Free"}{x.note&&<b className="repair"> · {x.note}</b>}</p></div></div>)}</div><aside className="agent-panel card"><div className="panel-title"><Bot size={16}/> Agent trace <span>LIVE</span></div>{plan.agentLog.map(([a,b])=><div className="trace" key={a}><div className="check-dot"><Check size={11}/></div><div><b>{a}</b><p>{b}</p></div></div>)}<img src={A+"route-optimizer.png"}/></aside></div></section>}

function SmartRoute({plan,goto}){if(!plan)return <Empty goto={goto}/>;let pts=plan.route.map((r,i)=>({name:r,x:15+i*25,y:55+(i%2? -24:18)}));return <section><PageTitle eyebrow="ROUTE INTELLIGENCE" title="The shortest story between experiences." sub="TripBuddy clusters the day by geography and pace instead of making you zig-zag."/><div className="route-grid"><div className="map-card card"><div className="map-toolbar"><span><Navigation size={14}/> Optimised route</span><b>{plan.route.length} stops</b></div><svg className="route-svg" viewBox="0 0 700 420"><defs><linearGradient id="route" x1="0" x2="1"><stop stopColor="#65e6c2"/><stop offset="1" stopColor="#8f7cff"/></linearGradient></defs><path d="M80 290 C180 160 260 300 350 170 S540 90 620 260" fill="none" stroke="#203a51" strokeWidth="18" strokeLinecap="round"/><path d="M80 290 C180 160 260 300 350 170 S540 90 620 260" fill="none" stroke="url(#route)" strokeWidth="4" strokeLinecap="round" strokeDasharray="7 8"/>{pts.map((p,i)=><g key={p.name}><circle cx={p.x*7} cy={p.y*6.2} r="14" fill="#0b1728" stroke="#65e6c2" strokeWidth="2"/><text x={p.x*7} y={p.y*6.2+4} textAnchor="middle" fill="#dffdf6" fontSize="10">{i+1}</text><text x={p.x*7} y={p.y*6.2+34} textAnchor="middle" fill="#8ea4bd" fontSize="11">{p.name}</text></g>)}</svg><div className="route-legend"><span><i className="dot green"/> Experience cluster</span><span><i className="dot purple"/> AI route</span><span>Transit time minimised</span></div></div><div className="route-insights"><div className="card insight"><span className="pill">WHY THIS ROUTE</span><h3>Geographic clustering</h3><p>Morning and evening experiences are grouped to reduce unnecessary transfers.</p><div className="insight-number">{Math.max(18,plan.route.length*11)}%</div><small>estimated transit friction avoided</small></div><div className="card insight"><span className="pill">PACE CHECK</span><h3>{plan.pace} rhythm</h3><div className="pace-bars"><i/><i/><i/><i/><i/></div><p>Activity density is adjusted to preserve your preferred travel pace.</p></div></div></div></section>}

function GroupHub({members,setMembers,toast}){const prefs=["Heritage","Food","Nature","Culture","Adventure","Shopping"];async function mediate(){let r=await fetch(`${API}/group/mediate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({members})});let d=await r.json();toast(`Consensus: ${d.consensus.join(" · ")} · ${d.confidence}% confidence`)}function update(i,p){setMembers(members.map((m,idx)=>idx===i?{...m,preferences:m.preferences.includes(p)?m.preferences.filter(x=>x!==p):[...m.preferences,p]}:m))}return <section><PageTitle eyebrow="GROUP MEDIATION ENGINE" title="Make everyone's trip count." sub="TripBuddy finds the overlap instead of making one traveller compromise."/><div className="group-grid"><div className="members">{members.map((m,i)=><div className="member card" key={m.name}><div className="member-top"><div className="member-avatar">{m.name[0]}</div><div><h3>{m.name}</h3><span>Traveller {i+1}</span></div></div><div className="chips">{prefs.map(p=><button key={p} className={m.preferences.includes(p)?"chip on":"chip"} onClick={()=>update(i,p)}>{p}</button>)}</div></div>)}<button className="add-member" onClick={()=>setMembers([...members,{name:`Friend ${members.length}`,preferences:["Food"]}])}><Plus size={15}/> Add traveller</button></div><div className="consensus card"><span className="pill">GROUP AI</span><div className="consensus-ring"><Users size={28}/><b>{Math.min(96,55+members.length*9+12)}%</b><small>confidence</small></div><h2>Balanced itinerary</h2><p>The mediation agent weighs preference overlap, budget fairness and pace compatibility.</p><button className="primary full" onClick={mediate}><Sparkles size={15}/> Run group mediation</button><div className="consensus-list"><span>Decision factors</span><b>Interest overlap</b><b>Budget fairness</b><b>Pace compatibility</b></div></div></div></section>}

function ExecutionHub({plan,toast}){const [quotes,setQuotes]=useState(null),[selected,setSelected]=useState([]);async function get(){let r=await fetch(`${API}/bookings/quote`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destination:plan?.destination,budget:plan?.budget||18000})});let d=await r.json();setQuotes(d.quotes)}function book(q){setSelected([...selected,q.type]);toast(`${q.type} reserved in demo mode — no real payment made.`)}return <section><PageTitle eyebrow="AUTONOMOUS EXECUTION" title="From plan to action." sub="A safe booking hand-off that demonstrates how TripBuddy can execute the itinerary."/><div className="execution-banner card"><div className="execution-orb"><Zap size={23}/></div><div><b>Execution Agent</b><p>Finds inventory → checks constraints → prepares reservations → asks for final approval.</p></div><span className="pill bright">APPROVAL GATE</span></div><div className="quote-grid">{(quotes||[{type:"Flight",provider:"TripBuddy Air",detail:"Round trip · best value",price:Math.round((plan?.budget||18000)*.24),badge:"Ready"},{type:"Stay",provider:"TripBuddy Stays",detail:"4-star · breakfast",price:Math.round((plan?.budget||18000)*.28),badge:"Recommended"},{type:"Dining",provider:"TripBuddy Tables",detail:"3 curated reservations",price:Math.round((plan?.budget||18000)*.12),badge:"AI curated"}]).map(q=><div className={`quote card ${selected.includes(q.type)?"selected":""}`} key={q.type}><div className="quote-icon">{q.type==="Flight"?<Plane size={18}/>:q.type==="Stay"?<Hotel size={18}/>:<Utensils size={18}/>}</div><span className="pill">{q.badge}</span><h3>{q.type}</h3><b>{q.provider}</b><p>{q.detail}</p><strong>{money(q.price)}</strong><button className={selected.includes(q.type)?"secondary full":"primary full"} onClick={()=>book(q)}>{selected.includes(q.type)?<><Check size={15}/> Reserved</>:<>Reserve in demo <ArrowRight size={15}/></>}</button></div>)}</div><div className="execution-foot"><button className="ghost" onClick={get}><RefreshCw size={15}/> Refresh provider quotes</button><span><ShieldCheck size={15}/> Demo bookings never charge money.</span></div></section>}

function Budget({plan,members,toast}){const total=plan?.estimated||18000,[split,setSplit]=useState(null);const rows=[['Stay',plan?.stay||Math.round(total*.28)],['Transport',plan?.transport||Math.round(total*.22)],['Food',plan?.food||Math.round(total*.22)],['Experiences',plan?.activities||Math.round(total*.18)]];async function make(){let r=await fetch(`${API}/split`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({total,members:members.map(x=>x.name)})});let d=await r.json();setSplit(d.split);toast("UPI-style group split prepared — no payment initiated.")}return <section><PageTitle eyebrow="BUDGET + MULTI-PAYER" title="Every rupee has a reason." sub="Micro-budget guardrails keep the plan aligned before anyone books."/><div className="budget-grid"><div className="card budget-card"><div className="budget-total"><span>Estimated trip spend</span><b>{money(total)}</b><small>within your target of {money(plan?.budget||18000)}</small></div>{rows.map(([x,n])=><div className="bar-row" key={x}><div><span>{x}</span><b>{money(n)}</b></div><div className="bar"><i style={{width:`${Math.min(100,n/total*100)}%`}}/></div></div>)}</div><div className="card split-card"><span className="pill">UPI-STYLE GROUP SPLIT</span><h2>Transparent group payments.</h2><p>Prepare each traveller's share before the booking hand-off. This demo stops before any real payment.</p><button className="primary" onClick={make}><Split size={15}/> Generate split</button>{split&&<div className="split-list">{split.map(x=><div key={x.name}><span>{x.name}</span><b>{money(x.amount)}</b><small>{x.status}</small></div>)}</div>}</div></div></section>}

function TravelDNA({trip,setTrip}){const levels={Relaxed:"Low",Balanced:"Medium",Fast:"High"};return <section><PageTitle eyebrow="PERSONALISATION ENGINE" title="Your Travel DNA." sub="A compact profile the planning agents use to personalise every decision."/><div className="dna-grid"><div className="card dna-card"><div className="dna-header"><div className="dna-avatar">T</div><div><h2>Traveller profile</h2><p>Updated from your current trip brief.</p></div></div><div className="dna-score"><span>Personalisation score</span><b>92</b><small>/100</small></div><DNAItem label="Pace" value={trip.pace} detail={levels[trip.pace]||"Medium"}/><DNAItem label="Budget sensitivity" value={money(trip.budget)} detail="Micro-budget guard active"/><DNAItem label="Top interests" value={trip.interests.slice(0,3).join(" · ")} detail="Weighted highest"/></div><div className="card dna-visual"><span className="pill bright">TRAVEL DNA</span><div className="radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-shape"/></div><div className="radar-labels"><span>Heritage</span><span>Food</span><span>Nature</span><span>Adventure</span></div></div></div></section>}
function DNAItem({label,value,detail}){return <div className="dna-item"><span>{label}</span><div><b>{value}</b><small>{detail}</small></div></div>}
function Empty({goto}){return <div className="empty card"><Bot size={30}/><h2>No trip built yet</h2><p>Create a trip first and let the agents generate your workspace.</p><button className="primary" onClick={()=>goto("create")}>Create a trip <ArrowRight size={15}/></button></div>}
